import os, asyncio, re
from playwright.async_api import async_playwright
B = os.environ.get("BASE", "http://localhost:3000")
DOSSIER = os.environ.get("DOSSIER")
res = []
def ok(n, c, d=""): res.append(("PASS" if c else "FAIL", n, str(d)[:150]))
VIS = "()=>[...document.querySelectorAll('.news-cell')].filter(c=>!c.hidden && !c.closest('[hidden]')).length"
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        pg = await (await b.new_context(viewport={"width": 1440, "height": 900})).new_page()
        await pg.goto(B + "/", wait_until="networkidle")
        ok("nav: News link in header", await pg.evaluate("!!document.querySelector('.nav-desktop a[href=\"/news\"]')"))
        ok("footer: News link", await pg.evaluate("!!document.querySelector('.site-footer a[href=\"/news\"]')"))
        await pg.click(".nav-desktop a[href='/news']"); await pg.wait_for_url("**/news"); await pg.wait_for_timeout(600)
        ok("nav: News marked current", await pg.evaluate("document.querySelector('.nav-desktop a[aria-current=page]')?.getAttribute('href')==='/news'"))
        ok("14 articles rendered", await pg.evaluate(VIS) == 14)
        dates = await pg.evaluate("[...document.querySelectorAll('.news-card time')].map(t=>t.getAttribute('datetime'))")
        ok("reverse chronological", dates == sorted(dates, reverse=True), dates[:4])
        links = await pg.evaluate("[...document.querySelectorAll('a.news-read')].map(a=>[a.href,a.target,a.rel])")
        ok("16 external links (14 articles + 2 references), new tab, noopener", len(links) == 16 and all(t == "_blank" and "noopener" in r for _, t, r in links), len(links))
        if DOSSIER:
            urls = set(re.findall(r"https?://\S+", open(DOSSIER, encoding="utf-8").read()))
            ok("every link matches a dossier URL exactly", {u for u, _, _ in links} == urls, {u for u, _, _ in links} ^ urls)
            heads = [h.strip() for h in re.findall(r"^## \d+\. (.+)$", open(DOSSIER, encoding="utf-8").read(), re.M)]
            page = await pg.evaluate("document.body.textContent")
            ok("all 14 dossier headlines present verbatim", all(h in page for h in heads) and len(heads) == 14, [h for h in heads if h not in page])
        await pg.click(".news-filter-row button:has-text('2025')"); await pg.wait_for_timeout(1500)
        ok("year 2025 → 9", await pg.evaluate(VIS) == 9 and "year=2025" in pg.url)
        op = await pg.evaluate("[...document.querySelectorAll('.news-cell')].filter(c=>!c.hidden&&!c.closest('[hidden]')).map(c=>getComputedStyle(c).opacity)")
        ok("filtered cards fully visible", all(float(x) > .99 for x in op))
        await pg.click("button.filter-chip:has-text('BIHA Activities')"); await pg.wait_for_timeout(500)
        st = await pg.evaluate("document.querySelector('.news-status [role=status]').textContent")
        ok("2025 ∩ BIHA Activities → 4, announced", await pg.evaluate(VIS) == 4 and "BIHA" in st, st)
        await pg.reload(wait_until="networkidle"); await pg.wait_for_timeout(700)
        ok("filters restored from URL", await pg.evaluate(VIS) == 4)
        await pg.click(".news-reset"); await pg.wait_for_timeout(400)
        ok("reset shows all", await pg.evaluate(VIS) == 14 and "year=" not in pg.url)
        await pg.click(".news-filter-row button:has-text('2026')"); await pg.wait_for_timeout(300)
        ok("2026 → 5; 2025 group hidden", await pg.evaluate(VIS) == 5 and await pg.evaluate("[...document.querySelectorAll('.news-year')].filter(s=>!s.hidden).length") == 1)
        ok("categories without 2026 coverage disabled", await pg.evaluate("document.querySelector(\"button.filter-chip:disabled\")!==null"))
        await pg.goto(B + "/news?category=Awards%20%26%20Recognition", wait_until="networkidle"); await pg.wait_for_timeout(500)
        ok("deep link category=Awards & Recognition → 2", await pg.evaluate(VIS) == 2)
        ok("institutional references section with 2 cards", await pg.evaluate("document.querySelectorAll('#references .ref-card').length") == 2)
        ok("one h1", await pg.evaluate("document.querySelectorAll('h1').length") == 1)
        await b.close()
    for r in res: print(*r)
    print("pass", sum(r[0] == "PASS" for r in res), "/", len(res))
asyncio.run(main())
